defaults:
  - models: discrete_action_model
  # - models: continuous_action_model

# Model configuration
ckpt_path: /Users/yixunhu/Home/pton_ECE_G1/MAE_549_Intro_to_Robo/HW_MAE_549/F2025/final_project/drone/checkpoints/best_drone_model_our_stack_state_discrete_pretrain_1210(3).pth

# Data configuration
data_dir: /Users/yixunhu/Home/pton_ECE_G1/MAE_549_Intro_to_Robo/HW_MAE_549/F2025/final_project/drone/datasets/imitation_data
image_size: [224, 224]
augment: False # Always false for inference

# Logging configuration
log_dir: logs

# Drone configuration
group_number: 13 # Your group number
camera_id: 0
hover_height: 0.5
fly_steps: 2000
crop_top: 80 # How much of the top of the camera image to crop out